# Generated by Django 2.2.6 on 2019-10-29 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(max_length=128)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('data_inicio', models.DateTimeField()),
                ('salario_liquido', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('vinculo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('tel_residencial', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,14}$')])),
                ('tel_comercial', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,14}$')])),
                ('ocupacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocupacao', to='testapp.Ocupacao')),
            ],
        ),
    ]
